spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driverClassName: org.postgresql.Driver
    username: postgres
    password: 1234
    url: jdbc:postgresql://localhost:5432/springdata
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: true
telegram:
  bot:
    token: "6366579590:AAH6f4tXdNmANmB_xbWSACzV4D3ri0A7Mfw"